network:
    version: 2
    renderer: networkd
    ethernets:
     enp3s0:
       dhcp4: no


    bridges:
     br0:
       macaddress: f0:2f:74:85:da:6e
       interfaces:
         - enp3s0
       addresses:
         - 172.20.0.242/23
       gateway4: 172.20.0.1
       nameservers:
        addresses: [172.20.0.250, 172.20.0.1]
        search: [tko22.local, tko22]
       dhcp4: no
       dhcp6: no
