network:
    version: 2
    renderer: networkd
    ethernets:
     enp3s0:
       dhcp4: no


    bridges:
     br0:
       macaddress: f0:2f:74:85:da:6e
       interfaces:
         - enp3s0
       addresses:
         - 10.10.0.22/16
       gateway4: 10.10.1.1
       nameservers:
        addresses: [10.10.13.10, 10.10.0.3]
        search: [tko22.local]
       dhcp4: no
       dhcp6: no
